### ISSUE TITLE
Remove references to testing

### ISSUE THREAD

**Issue by tylercollier-devmtn** [DevMountain/react-5-mini#3]
@JRobber 
I think saying "run the tests" in the opening paragraph of the README is too much for this project, which is meant as a mini project. If testing is really meant to be addressed in this project, there should be some instructions about tests; as it is, there is no mention of tests other than a variable must be changed.

If the tests are meant for DevMountain staff, as opposed to students, that should be made clear.

**Comment by devlemire** [comment]
I agree 100%, we don't use tests in any of the minis and it just adds noise to the project. I'll be removing it in v2.
